### ISSUE TITLE
Wix Product Query

### ISSUE THREAD

**Issue by Caligulaa** [wix/wix-commerce-ticketing-nextjs-template#208]
Query by slug is not implemented properly. Always returning the same product.

**Comment by orunto** [comment]
has this been solved?

**Comment by netanelgilad** [comment]
> has this been solved?

Yep, there was a bug in a specific version of the stores SDK at the time, but it has been resolved since then.
The query by slug for product is working on the product page, you can see it in action in this page here:
https://netlify.commerce-ticketing-demo.wix.dev/product-page/sweatshirt
